<a href="https://colab.research.google.com/github/sgshaillesh2004-tech/Api-ethics-assignment/blob/Maasai/categorical_encoding_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, RobustScaler


data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
df

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

Task-1

In [ ]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [ ]:
df = pd.get_dummies(df, columns=['City'], drop_first=True)

In [ ]:
size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size'] = df['Size'].map(size_mapping)

Task 2

In [ ]:
scaler = RobustScaler()

df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

In [ ]:
df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -0.411765 -0.250000       False         True
1       0     2  0.764706  0.767857        True        False
2       0     1  0.000000  0.000000       False        False
3       1     2  1.647059  1.303571       False         True
4       0     0 -0.235294 -0.232143        True        False